In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("bosua.csv")
df.head()

,cow_id,date,body_temperature,activity_level,feed_intake,milk_yield,rumination_time,heart_rate,steps,health_status
0,C001,3/1/2024,38.70,62.93,24.94,35.62,403,70,7395,healthy
1,C001,3/2/2024,38.81,57.96,24.63,25.68,387,73,3204,healthy
2,C001,3/3/2024,37.81,56.57,19.96,29.57,356,63,7258,healthy
3,C001,3/4/2024,38.41,66.01,18.73,25.28,427,65,5950,healthy
4,C001,3/5/2024,38.26,60.62,21.19,37.26,419,65,6487,healthy

In [2]:
features = df[['body_temperature',
               'activity_level',
               'feed_intake',
               'milk_yield',
               'rumination_time',
               'heart_rate']]

features.head()

,body_temperature,activity_level,feed_intake,milk_yield,rumination_time,heart_rate
0,38.70,62.93,24.94,35.62,403,70
1,38.81,57.96,24.63,25.68,387,73
2,37.81,56.57,19.96,29.57,356,63
3,38.41,66.01,18.73,25.28,427,65
4,38.26,60.62,21.19,37.26,419,65

In [3]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(features)

In [4]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)

df['cluster'] = kmeans.fit_predict(X)

df.head()

,cow_id,date,body_temperature,activity_level,feed_intake,milk_yield,rumination_time,heart_rate,steps,health_status,cluster
0,C001,3/1/2024,38.70,62.93,24.94,35.62,403,70,7395,healthy,2
1,C001,3/2/2024,38.81,57.96,24.63,25.68,387,73,3204,healthy,2
2,C001,3/3/2024,37.81,56.57,19.96,29.57,356,63,7258,healthy,1
3,C001,3/4/2024,38.41,66.01,18.73,25.28,427,65,5950,healthy,1
4,C001,3/5/2024,38.26,60.62,21.19,37.26,419,65,6487,healthy,1

In [ ]:
plt.figure(figsize=(8,6))

plt.scatter(df['activity_level'],
            df['milk_yield'],
            c=df['cluster'])

plt.xlabel("Activity Level (Mức độ hoạt động)")
plt.ylabel("Milk Yield (Sản lượng sữa)")
plt.title("Cow Health Clustering")

plt.show()